- name: configure yum repos for rabbitmq erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: rabbitmq-server
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: installing rabbitmq
  ansible.builtin.package:
    name: rabbitmq-server
    state: present

- name: start and enable rabbitmq server
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: setting up user & permissions
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('aws_ssm', '/roboshop/{{env}}/rabbitmq_user', region='us-east-1', decrypt=True ) }}"
    password: "{{ lookup('aws_ssm', '/roboshop/{{env}}/rabbitmq_pass', region='us-east-1', decrypt=True ) }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

# - name: setting up user 
#   ansible.builtin.command: "rabbitmqctl add_user {{rq_user}} {{rq_passwd}}"

# - name: setting-up permissions
#   ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"