- name: app-setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: setting up go
  ansible.builtin.import_role:
    name: common
    tasks_from: go

- name: copying service file and systemd setup
  ansible.builtin.role:
    name: common
    tasks_from: sydtemd
      

  
  