- name: creating user roboshop
  ansible.builtin.user:
    name: roboshop

- name: recursively removing app directory
  ansible.builtin.file:
    path: /app
    state: absent
      
- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory
  
- name: "downloading file {{component}}.zip"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp
  
- name: unarchile the zip file
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes