- name: instaling maven
  ansible.builtin.package:
    name: maven
    state: present

- name: downloading the dependencies
  ansible.builtin.command: mvn clean package
  args: 
    chdir: /app

- name: renaming shipping jar file
  ansible.builtin.command: "mv target/{{component}}-{{shipping_version}}.jar {{component}}.jar"
  args: 
    chdir: /app