- name: installing mysql client
  ansible.builtin.package:
    name: mysql
    state: present

- name: checking cites schema exists or not
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: cities_schema

- name: debug the shippinmg count
  ansible.builtin.debug:
    msg: "cities count:{{cities_schema}}"

- name: loading the shipping schema
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/schema/shipping.sql 
  when: cities_schema.stdout == "0"