- name: disbling existing and enabling nodejs
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: installing nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: instaling dependencie
  ansible.builtin.command: npm install
  args:
    chdir: /app